spring:
  datasource:
    url: jdbc:mysql://120.27.215.26:3306/testdb
    username: testdb
    password: ijBNDxmwPBywdDbi
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
server:
  servlet:
    context-path: /api